account/urls.py
from django.conf.urls import url

from .views import dashboard, update_profile


app_name = 'account' # namespace for this app

urlpatterns = [
    url(r'^$', dashboard, name='dashboard'),
    url(r'^update/$', update_profile, name='update_profile'),
]

service/urls.py
from django.conf.urls import url

from .views import (service_create,
                    service_detial,
                    service_list,
                    my_service_list,
                    service_update,)

app_name = 'service'

urlpatterns = [
    url(r'^add/$', service_create, name='service_add'),
    url(r'^update/(?P<pk>\d+)/$', service_update, name='service_update'),
    url(r'^list/$', service_list, name='service_list'),
    url(r'^my_service_list/$', my_service_list, name='my_service_list'),
    url(r'^(?P<pk>\d+)/$', service_detial, name='service_detail'),
]

servicebox_project/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^account/', include('account.urls')),
    url(r'^registration/', include('registration.urls')),
    url(r'^service/', include('service.urls')),
    url(r'^', include('website.urls')),
]

website/urls.py
from django.conf.urls import url

from .views import home, search


app_name = 'website'

urlpatterns = [
    url(r'^$', home, name='home'),
    url(r'^search/$', search, name='search'),
]

website/models.py
from django.db import models

# Create your models here.

website/forms.py
from django import forms


class SearchForm(forms.Form):
    q = forms.CharField(label='', widget=forms.TextInput(attrs={'placeholder':'search what you want!'}))

website/views.py
from django.db.models import Q
from django.shortcuts import render
from algoliasearch_django import raw_search

from service.models import Service
from .forms import SearchForm


def home(request):
    context = {}
    top_service_list = Service.objects.all()

    context['top_service_list'] = top_service_list
    return render(request, 'website/home.html', context)


def search(request):
    context = {}
    query_string = request.GET.get('q')
    if query_string:
        # setting custom search result
        results = Service.objects.filter(Q(name__icontains=query_string) |
                                         Q(description__icontains=query_string) |
                                         Q(provider__first_name__contains=query_string) |
                                         Q(provider__last_name__contains=query_string)).distinct()
        context['results'] = results

        # adding algolia search result
        algolia_results = raw_search(Service, query_string)
        context["algolia_results"] = algolia_results

    form = SearchForm(request.GET or None)
    context['form'] = form
    return render(request, 'website/search_result.html', context)

website/templates/website/home.html
{% extends 'base.html' %}

{% block content %}
    <h2>Search Service</h2>
    <form method="get" action="{% url 'website:search' %}">
        <input name="q" type="text" placeholder="what you want!?">
        <input type="submit">
    </form>

    <h2>Top Services</h2>
    {% for service in top_service_list %}
        <p><a href="{% url 'service:service_detail' pk=service.pk %}">{{ service.name }}</a> -{{ service.created }}</p>
    {% endfor %}

{% endblock %}

website/templates/website/search_result.html
{% extends 'base.html' %}

{% block content %}
    <h2>Search Service</h2>
    <form method="get" action="{% url 'website:search' %}">
        {{ form.as_p }}
        <input type="submit">
    </form>

    {% if results %}
        <hr><br>
        <b>Builtin Search Results</b>
        {% for result in results %}
            <p><a href="{% url 'service:service_detail' pk=result.pk %}">{{ result }}</a></p>
        {% endfor %}
    {% else %}
        <p>No result found on builtin search</p>
    {% endif %}


    {% if results %}
        <hr><br>
        <b>Algolia Search result</b>
        {% for result in algolia_results.hits %}
            <p><a href="{% url 'service:service_detail' pk=result.objectID %}">{{ result.name }}</a></p>
        {% endfor %}
    {% else %}
        <p>No result found on algolia search</p>
    {% endif %}

{% endblock %}