account/urls.py
from django.conf.urls import url

from .views import dashboard, update_profile


app_name = 'account' # namespace for this app

urlpatterns = [
    url(r'^$', dashboard, name='dashboard'),
    url(r'^update/$', update_profile, name='update_profile'),
]

service/urls.py
from django.conf.urls import url

from .views import (service_create,
                    service_detial,
                    service_list,
                    my_service_list,
                    service_update,)

app_name = 'service'

urlpatterns = [
    url(r'^add/$', service_create, name='service_add'),
    url(r'^update/(?P<pk>\d+)/$', service_update, name='service_update'),
    url(r'^list/$', service_list, name='service_list'),
    url(r'^my_service_list/$', my_service_list, name='my_service_list'),
    url(r'^(?P<pk>\d+)/$', service_detial, name='service_detail'),
]

servicebox_project/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^account/', include('account.urls')),
    url(r'^registration/', include('registration.urls')),
    url(r'^service/', include('service.urls')),
    url(r'^', include('website.urls')),
]

service/models.py
from django.contrib.auth.models import User
from django.db import models
from django.shortcuts import reverse


class ServiceManager(models.Manager):
    def my_service_list(self, id):
        # filter and return all services created by current user
        return self.filter(provider__id=id)


class Service(models.Model):
    name            = models.CharField(max_length=255)
    description     = models.TextField()

    provider        = models.ForeignKey(User, on_delete=models.CASCADE)

    created         = models.DateTimeField(auto_now_add=True)
    updated         = models.DateTimeField(auto_now=True)

    objects         = ServiceManager()

    def get_absolute_url(self):
        return reverse('service:service_detail', kwargs={'pk': self.pk})

    def __str__(self):
        return self.name

service/forms.py
from django import forms

from .models import Service


class ServiceModelForm(forms.ModelForm):
    class Meta:
        model = Service
        exclude = ['provider']  # provider will be add in view, for security.

service/views.py
from django.contrib.auth.decorators import login_required
from django.http import Http404
from django.shortcuts import render, redirect, get_object_or_404

from .models import Service
from .forms import ServiceModelForm


def service_detial(request, pk):
    # detail page for single service object
    service = get_object_or_404(Service, pk=pk)
    context = {
        'service': service
    }
    return render(request, 'service/service_detail.html', context)


def service_list(request):
    # all service list (it can be top list)
    all_services = Service.objects.all()
    context = {
        'service_list': all_services
    }
    return render(request, 'service/service_list.html', context)


def my_service_list(request):
    # services current user created
    my_services = Service.objects.my_service_list(request.user.id)
    context = {
        'service_list': my_services
    }
    return render(request, 'service/service_list.html', context)


@login_required
def service_create(request):
    if request.method == 'POST':
        form = ServiceModelForm(request.POST)
        if form.is_valid():
            # ServiceModelForm not creating 'User' ForeignKey
            # thus it not adding service.provider field to current user
            # so we have to add it manually!
            form.instance.provider = request.user
            form.save()
            # redirect user to newly created service detail page
            return redirect(form.instance)
    else:
        form = ServiceModelForm()
    return render(request, 'service/service_create_form.html', {'form': form})


@login_required
def service_update(request, pk):
    service = get_object_or_404(Service, pk=pk)

    # checking if the current user is creator of
    # this service, only creators can update their services
    if not service.provider.id == request.user.id:
        raise Http404 # this http code should be change to 401 not authorized

    if request.method == 'POST':
        form = ServiceModelForm(request.POST, instance=service)
        if form.is_valid():
            form.save()
            return redirect(service)
    else:
        form = ServiceModelForm(instance=service)
    return render(request, 'service/service_create_form.html', {'form': form})

service/templates/service/service_create_form.html
{% extends 'base.html' %}

{% block title %}Service | {{ block.super }}{% endblock %}

{% block content %}
    <form action="" method="post">{% csrf_token %}
        {{ form.as_p }}

        <input type="submit"/>
    </form>
{% endblock %}

service/templates/service/service_detail.html
{% extends 'base.html' %}

{% block title %}Service | {{ block.super }}{% endblock %}


{% block content %}

            <strong>ID: </strong>{{ service.id }}<br/>
            <strong>Name: </strong>{{ service.name }}<br/>
            <strong>Description: </strong>{{ service.description }}<br/>
            <strong>Provider: </strong>{{ service.provider.username }}<br/>
            <strong>created: </strong>{{ service.created }}<br/>
            <strong>updated: </strong>{{ service.updated }}<br/>

    {% if request.user.id == service.provider.id %}
        <a href="{% url 'service:service_update' pk=service.pk %}">edit</a>
    {% endif %}

{% endblock %}

service/templates/service/service_list.html
{% extends 'base.html' %}

{% block title %}Service | {{ block.super }}{% endblock %}

{% block content %}
    <table>
        <thead>
        <tr>
            <th scope="col">Reg. ID</th>
            <th scope="col">Name</th>
            <th scope="col">Description</th>
        </tr>
        </thead>
        <tbody>
        {% for service in service_list %}
            <tr>
                <th>{{ service.id }}</th>
                <td><a href="{% url 'service:service_detail' pk=service.pk %}">
                    {{ service.name }}
                </a></td>
                <td>{{ service.description }}</td>
            </tr>
        {% empty %}
            <p>No Service Created yet.</p>
        {% endfor %}
    </table>

{% endblock %}