account/urls.py
from django.conf.urls import url

from .views import dashboard, update_profile


app_name = 'account' # namespace for this app

urlpatterns = [
    url(r'^$', dashboard, name='dashboard'),
    url(r'^update/$', update_profile, name='update_profile'),
]

registration/urls.py
from django.conf.urls import url
from django.contrib.auth.views import login, logout

from .views import user_signup


app_name = 'registration' # namespace for this app

urlpatterns = [
    url(r'^signup/$', user_signup, name='signup'),
    url(r'^login/$', login, {'template_name': 'login.html'}, name='login'),
    url(r'^logout/$',logout, {'next_page': '/'}, name='logout'),
]

service/urls.py
from django.conf.urls import url

from .views import (service_create,
                    service_detial,
                    service_list,
                    my_service_list,
                    service_update,)

app_name = 'service'

urlpatterns = [
    url(r'^add/$', service_create, name='service_add'),
    url(r'^update/(?P<pk>\d+)/$', service_update, name='service_update'),
    url(r'^list/$', service_list, name='service_list'),
    url(r'^my_service_list/$', my_service_list, name='my_service_list'),
    url(r'^(?P<pk>\d+)/$', service_detial, name='service_detail'),
]

servicebox_project/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^account/', include('account.urls')),
    url(r'^registration/', include('registration.urls')),
    url(r'^service/', include('service.urls')),
    url(r'^', include('website.urls')),
]

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    {% block css %}
    {% endblock %}

</head>
<body>
    <div>
        {% include 'header.html' %}

        {% block content %}
        {% endblock %}

        {% block javascript %}
        {% endblock %}
    </div>
</body>
</html>

templates/header.html
<ulzz>
    <li><a href="/">Home</a></li>

    {% if request.user.is_authenticated %}
        <li><a href="{% url 'account:dashboard' %}">Dashboard</a></li>
        <li><a href="{% url 'service:service_add' %}">Add Service</a></li>
        <li><a href="{% url 'service:my_service_list' %}">My Services</a></li>
        <li><a href="{% url 'registration:logout' %}">Logout</a></li>
    {% else %}
        <li><a href="{% url 'registration:signup' %}">Registration</a></li>
        <li><a href="{% url 'registration:login' %}?next={{ request.path|urlencode }}">Login</a></li>
    {% endif %}
</ulzz>

templates/login.html
{% extends 'base.html' %}

{% block title %}Login | {{ block.super }}{% endblock %}

{% block content %}
    <div class="col-md-4 col-md-offset-4">
        <div class="form-group">
            <p class="help-block">
               Username: admin
            </p>
            <p class="help-block">
               Password: $uP3r63cR37
            </p>
            <form method="post">{% csrf_token %}
                {{ form.as_p }}
                <input type="hidden" name="next" value="{{ request.GET.next }}">
                <input type="submit" value="Login" class="btn btn-default center-block"/>
            </form>
        </div>
    </div>
{% endblock %}